package numbers;

import java.util.Scanner;

/**
 * Perfect Number is a positive integer that is equal to the sum of its proper
 * divisors, which is sum of its positive divisors excluding the number itself.
 * For eg: 6 is perfect number: => 6 = 1 + 2 + 3 (sum of all its positive
 * divisors). Similarly, the next perfect number is 28 => (1 + 2 + 4 + 7 + 14).
 * <p>
 * The first four prime numbers are generated by the formula (2^(p-1))*(2^p-1)
 * where P is prime number.
 * <p>
 * For example:
 * for p = 2: 21(22 − 1) = 6
 * for p = 3: 22(23 − 1) = 28
 * for p = 5: 24(25 − 1) = 496
 * for p = 7: 26(27 − 1) = 8128.
 *
 * @author Pavitra
 */

public class PerfectNumber {
    static int number;

    public static void main(String[] args) {
        System.out.println("Enter the number to check for perfect number:");
        System.out.print("> ");
        Scanner input = new Scanner(System.in);
        number = input.nextInt();
        input.close();

        PerfectNumber pnObj = new PerfectNumber();
        boolean checkNumber = pnObj.checkPerfectNumber(number);
        pnObj.printResult(checkNumber);
    }

    private boolean checkPerfectNumber(int number) {
        int sum = 0;
        for (int divisor = 1; divisor < number; divisor++) {
            if ((number % divisor) == 0) {
                sum = sum + divisor;
            }
        }
        return sum == number;
    }

    private void printResult(boolean perfectNumber) {
        if (perfectNumber)
            System.out.println(PerfectNumber.number + " is a perfect number");
        else
            System.out.println(PerfectNumber.number + " is not a perfect number!!!");
    }
}
